"""Level data for all worlds, written as ASCII tile maps.

Legend:
  .  air                       X  ground/dirt block
  B  brick (breakable if big)  =  solid block
  ?  ?-block with coin         M  ?-block with power-up
  U  ?-block with 1-up         -  one-way platform (jump through)
  [ ]  pipe top                { }  pipe body
  ( )  pipe top w/ Chomp Plant ^  spikes
  L  lava                      b  bridge (solid)
  C  coin                      A  checkpoint
  P  player spawn              F  flag (pole auto-extends down)
  E  Grub                      K  Shellback
  S  Spiny                     W  Flit (flying)
  o  moving platform (horiz)   v  moving platform (vert)
  H  Hopper (leaping frog)      D  Dozer (smart walker)
  T  turret block (fires)       R  rotating firebar
  J  springboard                *  boss

Levels are 15 rows tall; ground is usually rows 13-14 (standing row 12).
Design rules (enforced by game.reach, which models the jump physics):
  - pits <= 5 tiles wide; ledges <= 2 up when also moving sideways
  - ?/M/U blocks ~4 rows above the surface they're bumped from
  - no ceilings low enough to block a needed jump arc
"""

ROWS = 15


def blk(s):
    """Parse a chunk: strip empty edge lines, pad rows to equal width,
    bottom-align to ROWS rows of air."""
    lines = list(s.splitlines())
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    w = max(len(ln) for ln in lines) if lines else 0
    lines = [ln.ljust(w, ".") for ln in lines]
    pad = ["." * w] * (ROWS - len(lines))
    return pad + lines


def flat(w, h=2):
    return blk("\n".join(["X" * w] * h))


def gap(w):
    return blk("." * w)


def hcat(*chunks):
    return ["".join(rows) for rows in zip(*chunks)]


def roofed(body):
    """Cave/castle chunk: solid ceiling along the very top row."""
    rows = blk(body)
    rows[0] = "X" * len(rows[0])
    return rows


def pipe(h, plant=False, gap_after=0):
    """A pipe of height h standing on 2-thick ground."""
    top = "()" if plant else "[]"
    rows = [top] + ["{}"] * (h - 1) + ["XX", "XX"]
    c = blk("\n".join(rows))
    return hcat(c, flat(gap_after)) if gap_after else c


def stairs_up(steps=4):
    rows = []
    for r in range(steps):
        filled = (r + 1) * 2
        rows.append("." * (steps * 2 - filled) + "=" * filled)
    rows += ["X" * steps * 2] * 2
    return blk("\n".join(rows))


def stairs_down(steps=4):
    rows = []
    for r in range(steps):
        filled = (r + 1) * 2
        rows.append("=" * filled + "." * (steps * 2 - filled))
    rows += ["X" * steps * 2] * 2
    return blk("\n".join(rows))


def flag_zone(run=12, height=9):
    lines = ["." * (run // 2) + "F" + "." * (run - run // 2 - 1)]
    lines += ["." * run] * (height - 1)
    lines += ["X" * run] * 2
    return blk("\n".join(lines))


# ============================== WORLD 1: GREEN HILLS ==============================

def build_1_1():
    """Rolling Meadow — classic opener: gentle pacing, coins, first foes."""
    return hcat(
        blk("""
.........?M?........
....................
....................
...P...........E....
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
...?.B?B..............
......................
......................
........E....E........
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        pipe(2, gap_after=5), pipe(3, gap_after=6),
        blk("""
..........
...CCCC...
..C....C..
..........
XXX....XXX
XXX....XXX
"""),
        blk("""
.....CCCC...............
.....BBBB....?..........
........................
........................
..........K......E......
XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
...........CC.........
....CC....XXXX........
...XXXX...XXXX....E...
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
.......M............
....................
....................
.........A..........
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
....C....CC....C....
....................
XXXX....==....XXXXXX
XXXX....==....XXXXXX
"""),
        blk("""
..CCC............CCC....
..BBB............BBB....
........................
........................
..............E....E....
XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX
"""),
        pipe(3, gap_after=4),
        blk("""
.....U............
..................
..................
..........E.......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
....C......C........
....................
.....H........H.....
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
......CCC.......
......===.......
................
................
................
................
...J............
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
"""),
        blk("""
....C.....C.....
................
XXXX...XXX...XXX
XXXX...XXX...XXX
"""),
        stairs_up(4), flat(2), gap(3), stairs_down(4), flat(4),
        stairs_up(4), flag_zone(12),
    )


def build_1_2():
    """Dewdrop Cave — underground pillars, shelves and coin pockets."""
    return hcat(
        roofed("""
....P...........
................
............E...
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
"""),
        roofed("""
...CCCC.....CCCC......
...BBBB..M..BBBB......
......................
......................
......E.........E.....
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
......C.....C.........
...==....==....==..C..
...==....==....==.....
...==.S..==..E.==.....
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
......C.......
.....---......
..............
..............
XXXXX.....XXXX
XXXXX.....XXXX
"""),
        roofed("""
......CCCC............
......====............
......................
..==...........==.....
......................
.......S.......E......
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
...U..............
..................
..................
..........A.......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
...XXXXXXXXXXXX.....
...XXXXXXXXXXXX.....
....................
......S.....S.......
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
.....CCCCCC.......
.....CCCCCC.......
.....======.......
..................
..........K.......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
..............
..............
..............
....E.........
XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
"""),
        roofed("""
....D...........
....======......
................
................
..........E.....
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
"""),
        roofed("""
.....CCC..........
.....===..........
..................
..................
..................
..................
...J..........S...
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        stairs_up(3), flag_zone(12),
    )


def build_1_3():
    """Treetop Hop — first athletic level: islands over the void."""
    return hcat(
        blk("""
..........
....P.....
XXXXXXXXXX
XXXXXXXXXX
"""),
        blk("""
.............
.....C....C..
.............
.............
.............
.====...====.
.............
.............
"""),
        blk("""
.............
.........CC..
.............
.......====..
.............
.====........
.............
....W........
"""),
        blk("""
................
....C..C........
................
................
..o........====.
................
................
................
"""),
        blk("""
............
....?M?.....
............
............
............
.==========.
............
............
"""),
        blk("""
..............
....CC........
..............
.------.......
..........W...
.........====.
..............
..............
"""),
        blk("""
..........
..........
..........
..........
....A.....
.========.
..........
..........
"""),
        blk("""
............
...C...C....
............
............
..vv........
............
.......====.
............
"""),
        blk("""
...............
...CC.....CC...
...............
.=====.........
...............
........=====..
...............
...............
"""),
        blk("""
.............
....C...C....
.............
.............
.........H...
.====..====..
.............
.............
"""),
        blk("""
..........
...CCC....
...===....
..........
......W...
..........
..........
.J........
.===......
..........
"""),
        blk("""
.............
....C...C....
.............
.............
.............
.====..====..
.............
.............
"""),
        blk("""
............
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        stairs_up(3), flag_zone(12),
    )

def build_1_4():
    """Snapjaw Keep — first castle: spikes, lava and the boss."""
    return hcat(
        roofed("""
...P..........
..............
..............
XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
"""),
        roofed("""
...C.....C.....C......
......................
....E.........E.......
....^^....^^....^^....
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
.....C....C.........
....................
....==...==...==....
XXX..............XXX
XXXLLLLLLLLLLLLLLXXX
"""),
        roofed("""
....M.....CCC.....
..................
..................
........S.........
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
......................
....o.......o.....A...
......................
XXX.............XXXXXX
XXXLLLLLLLLLLLLLXXXXXX
"""),
        roofed("""
......W.....W.....
...C.....C........
...==...==...==...
XX..............XX
XXLLLLLLLLLLLLLLXX
"""),
        roofed("""
....C..........C....
....................
......R........R....
....................
....................
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
..................
..........T.......
....E.....X.......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
........................
........................
........................
...........*............
........................
XXX.bbbbbbbbbbbbbbb..XXX
XXXLLLLLLLLLLLLLLLLLLXXX
"""),
        flat(6),
    )

# ============================== WORLD 2: SANDY DUNES ==============================

def build_2_1():
    """Dune Dash — rolling dunes, plant pipes and speed."""
    return hcat(
        blk("""
...P......CC......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        pipe(2, plant=True, gap_after=6),
        blk("""
........?M?...........
......................
......................
....E........E........
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
.............CC.........
....CC......XXXX........
...XXXX..C..XXXX........
..XXXXXX....XXXX...S....
XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
....CCC.....
...C...C....
............
XXXX....XXXX
XXXX....XXXX
"""),
        pipe(3, plant=True, gap_after=5),
        blk("""
....C..C..C...........
....B..B..B...........
......................
.........K............
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..................
..................
..................
......A.......S...
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
....................
....................
..XXX..........XXX..
..XXX...CCCC...XXX..
..XXX..........XXX..
XXXXX....E....XXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        pipe(2, plant=True, gap_after=4),
        blk("""
...?.....?............
......................
....C......C..........
......................
XXXX...XXX....XXXXXXXX
XXXX...XXX....XXXXXXXX
"""),
        blk("""
....C.....C.........
....................
.....H.......D......
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..........T.......
..........X.......
....E.....X.......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        stairs_up(4), flag_zone(12),
    )


def build_2_2():
    """Oasis Pipes — a garden of pipes and the plants that live in them."""
    return hcat(
        blk("""
...P..........
XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
"""),
        pipe(2, gap_after=4), pipe(3, plant=True, gap_after=5),
        blk("""
.....B?BMB?B........
....................
....................
....E......K........
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        pipe(4, plant=True, gap_after=3),
        blk("""
......CCC.........
......BBB.........
..................
..................
XXXX.....XXXXXXXX
XXXX.....XXXXXXXX
"""),
        pipe(2, plant=True, gap_after=5),
        blk("""
....M.............
..................
..................
......A....K......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
....C......C......
...---....---.....
..................
..................
XXXX........XXXXXX
XXXX........XXXXXX
"""),
        pipe(3, plant=True, gap_after=4),
        blk("""
......U.............
....................
...CCC..............
...BBB..............
...........E....E...
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
....C......C......
..................
.....H.......H....
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
..........T.......
..........X.......
....E.....X.......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        pipe(2, gap_after=2), pipe(3, gap_after=2),
        stairs_up(3), flag_zone(12),
    )


def build_2_3():
    """Sky Ruins — crumbled towers in the sky."""
    return hcat(
        blk("""
..........
....P.....
XXXXXXXXXX
XXXXXXXXXX
"""),
        blk("""
.............
.....C....C..
.............
.............
.............
.====...====.
.............
.............
"""),
        blk("""
.............
.........CC..
.............
.......====..
.............
.====........
.............
....S........
"""),
        blk("""
................
....C..C........
................
................
..o........====.
................
................
................
"""),
        blk("""
............
....?M?.....
............
............
............
.==========.
............
............
"""),
        blk("""
..............
....CC........
..............
.------.......
..........W...
.........====.
..............
..............
"""),
        blk("""
..........
..........
..........
..........
....A.....
.========.
..........
..........
"""),
        blk("""
............
...C...C....
............
............
..vv........
............
.......====.
............
"""),
        blk("""
...............
...CC.....CC...
...............
.=====.........
...............
........=====..
...............
...............
"""),
        blk("""
.............
....C...C....
.............
.............
.........H...
.====..====..
.............
.............
"""),
        blk("""
............
....C..C....
............
.........W..
.....T......
.=========..
............
............
"""),
        blk("""
..........
...CCC....
...===....
..........
......W...
..........
..........
.J........
.===......
..........
"""),
        blk("""
............
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        stairs_up(3), flag_zone(12),
    )

def build_2_4():
    """Sunbaked Citadel — spikes, lava and a hardened King Snap."""
    return hcat(
        roofed("""
...P..........
..............
XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
"""),
        roofed("""
...C....C.....C.......
......................
....E......S.....E....
..^^....^^....^^......
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
.....C....C.........
....................
....==...==...==.W..
XX................XX
XXLLLLLLLLLLLLLLLLXX
"""),
        roofed("""
..().....M....()..
..{}..........{}..
..................
.......S..........
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
......................
...o......o.......A...
......................
XX..............XXXXXX
XXLLLLLLLLLLLLLLXXXXXX
"""),
        roofed("""
...CCC............
..................
.....W......S.....
....^^......^^....
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
....C..........C....
....................
......R........R....
....................
....................
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
..................
..........T.......
....E.....X.......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
........................
........................
........................
...........*............
........................
XXX.bbbbbbbbbbbbbbb..XXX
XXXLLLLLLLLLLLLLLLLLLXXX
"""),
        flat(6),
    )

# ============================== WORLD 3: FROSTPEAK ==============================

def build_3_1():
    """Slippery Slopes — momentum management on ice."""
    return hcat(
        blk("""
...P......CC......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
........?M?...........
......................
......................
...K...........E......
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
............CC..........
....CC.....XXXX.........
...XXXX....XXXX....K....
XXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
.....CCC......
....C...C.....
..............
XXXX....XXXXX
XXXX....XXXXX
"""),
        blk("""
....C..C..C..C........
....B..B..B..B........
......................
....K.........K.......
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..................
..................
.......A..........
....XX............
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
....C.....C.....C...
....................
XXXX...XXXX...XXXXXX
XXXX...XXXX...XXXXXX
"""),
        blk("""
......U.............
....................
....................
....................
....====............
..............E.....
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
....C.....C.........
....................
.....H.......D......
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
......CCC.......
......===.......
................
................
................
................
...J............
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
"""),
        blk("""
....C.....C.....
................
XXXX...XXX...XXX
XXXX...XXX...XXX
"""),
        stairs_up(4), flag_zone(12),
    )


def build_3_2():
    """Crystal Cavern — frozen underground with crystal shelves."""
    return hcat(
        roofed("""
....P...........
................
................
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
"""),
        roofed("""
...CCC.....M..........
...BBB................
......................
.....S.........E......
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
......C.......
.....---......
..............
..............
XXXXX.....XXXX
XXXXX.....XXXX
"""),
        roofed("""
.....CCCC.........
.....CCCC..U......
.....====.........
..................
.........K........
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
................
................
......A.........
....S...........
XXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX
"""),
        roofed("""
....C....C........
...---..---.......
..................
..................
XXXX.....XXXXXXXXX
XXXX.....XXXXXXXXX
"""),
        roofed("""
...XXXXXXXXXXXX.......
......................
....E.....E......E....
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
....D.......D.....
....==......==....
..................
..................
.........E........
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
.....CCC..........
.....===..........
..................
..................
..................
..................
...J..........S...
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        stairs_up(3), flag_zone(12),
    )


def build_3_3():
    """Blizzard Heights — icy islands in the storm."""
    return hcat(
        blk("""
..........
....P.....
XXXXXXXXXX
XXXXXXXXXX
"""),
        blk("""
.............
.....C....C..
.............
.............
.............
.====...====.
.............
.............
"""),
        blk("""
.............
.........CC..
.............
.......====..
.............
.====........
.............
....W........
"""),
        blk("""
................
....C..C........
................
................
..o........====.
................
................
................
"""),
        blk("""
............
....?M?.....
............
............
............
.==========.
............
............
"""),
        blk("""
..............
....CC........
..............
.------.......
..........W...
.........====.
..............
..............
"""),
        blk("""
..........
..........
..........
..........
....A.....
.========.
..........
..........
"""),
        blk("""
............
...C...C....
............
............
..vv........
............
.......====.
............
"""),
        blk("""
...............
...CC.....CC...
...............
.=====.........
...............
........=====..
...............
...............
"""),
        blk("""
.............
....C...C....
.............
.............
.........H...
.====..====..
.............
.............
"""),
        blk("""
..........
...CCC....
...===....
..........
......W...
..........
..........
.J........
.===......
..........
"""),
        blk("""
............
....C..C....
............
.........W..
.....T......
.=========..
............
............
"""),
        blk("""
............
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        stairs_up(3), flag_zone(12),
    )

def build_3_4():
    """King Snap's Fortress — the final gauntlet."""
    return hcat(
        roofed("""
...P..........
..............
XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
"""),
        roofed("""
...C..M.......C.......
......................
....E......S.....E....
..^^.....^^....^^.....
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
.....C....C.........
....................
....==...==...==.W..
XX................XX
XXLLLLLLLLLLLLLLLLXX
"""),
        roofed("""
..()....CCC...()..
..{}...=====..{}..
..................
.....S............
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        roofed("""
......................
...o......o.......A...
......................
XX..............XXXXXX
XXLLLLLLLLLLLLLLXXXXXX
"""),
        roofed("""
...C.....CCC........
....................
....W....S.....W....
..^^....^^^....^^...
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
....C.....C.....C....
.....................
.....R.....R.....R...
.....................
.....................
XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
.....T..........T....
.....X..........X....
..E..X.....S....X....
XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
"""),
        roofed("""
..........................
..........................
..........................
............*.............
..........................
XXX.bbbbbbbbbbbbbbbbb..XXX
XXXLLLLLLLLLLLLLLLLLLLLXXX
"""),
        flat(6),
    )

# ============================== REGISTRY ==============================

WORLDS = [
    {"name": "Green Hills", "theme": "grass"},
    {"name": "Sandy Dunes", "theme": "desert"},
    {"name": "Frostpeak", "theme": "ice"},
]

LEVELS = [
    {"world": 1, "index": 1, "name": "Rolling Meadow", "theme": "grass",
     "music": "grass", "build": build_1_1, "ice": False, "boss_hp": 0},
    {"world": 1, "index": 2, "name": "Dewdrop Cave", "theme": "cave",
     "music": "grass", "build": build_1_2, "ice": False, "boss_hp": 0},
    {"world": 1, "index": 3, "name": "Treetop Hop", "theme": "grass",
     "music": "grass", "build": build_1_3, "ice": False, "boss_hp": 0},
    {"world": 1, "index": 4, "name": "Snapjaw Keep", "theme": "castle",
     "music": "castle", "build": build_1_4, "ice": False, "boss_hp": 3},
    {"world": 2, "index": 1, "name": "Dune Dash", "theme": "desert",
     "music": "desert", "build": build_2_1, "ice": False, "boss_hp": 0},
    {"world": 2, "index": 2, "name": "Oasis Pipes", "theme": "desert",
     "music": "desert", "build": build_2_2, "ice": False, "boss_hp": 0},
    {"world": 2, "index": 3, "name": "Sky Ruins", "theme": "desert",
     "music": "desert", "build": build_2_3, "ice": False, "boss_hp": 0},
    {"world": 2, "index": 4, "name": "Sunbaked Citadel", "theme": "castle",
     "music": "castle", "build": build_2_4, "ice": False, "boss_hp": 4},
    {"world": 3, "index": 1, "name": "Slippery Slopes", "theme": "ice",
     "music": "ice", "build": build_3_1, "ice": True, "boss_hp": 0},
    {"world": 3, "index": 2, "name": "Crystal Cavern", "theme": "ice",
     "music": "ice", "build": build_3_2, "ice": True, "boss_hp": 0},
    {"world": 3, "index": 3, "name": "Blizzard Heights", "theme": "ice",
     "music": "ice", "build": build_3_3, "ice": True, "boss_hp": 0},
    {"world": 3, "index": 4, "name": "King Snap's Fortress", "theme": "castle",
     "music": "castle", "build": build_3_4, "ice": False, "boss_hp": 5},
]


def level_rows(idx):
    return LEVELS[idx]["build"]()


def validate():
    """Structural sanity checks; reach.validate_all() covers playability."""
    problems = []
    for lv in LEVELS:
        rows = lv["build"]()
        widths = {len(r) for r in rows}
        if len(widths) != 1:
            problems.append(f"{lv['name']}: ragged rows {widths}")
        if len(rows) != ROWS:
            problems.append(f"{lv['name']}: {len(rows)} rows")
        joined = "".join(rows)
        if "P" not in joined:
            problems.append(f"{lv['name']}: no player spawn")
        if lv["boss_hp"] == 0 and "F" not in joined:
            problems.append(f"{lv['name']}: no flag")
        if lv["boss_hp"] > 0 and "*" not in joined:
            problems.append(f"{lv['name']}: no boss")
    return problems
