"""Level data for all worlds, written as ASCII tile maps.

Legend:
  .  air                       X  ground/dirt block
  B  brick (breakable if big)  =  solid block
  ?  ?-block with coin         M  ?-block with power-up
  U  ?-block with 1-up         -  one-way platform (jump through)
  [ ]  pipe top                { }  pipe body
  ( )  pipe top w/ Chomp Plant ^  spikes
  L  lava                      b  bridge (solid)
  C  coin                      A  checkpoint
  P  player spawn              F  flag (pole auto-extends down)
  E  Grub                      K  Shellback
  S  Spiny                     W  Flit (flying)
  o  moving platform (horiz)   v  moving platform (vert)
  *  boss

Levels are 15 rows tall. Chunks are bottom-aligned then concatenated.
"""

ROWS = 15


def blk(s):
    """Parse a chunk: strip empty edge lines, pad rows to equal width,
    bottom-align to ROWS rows of air."""
    lines = [ln for ln in s.splitlines()]
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    w = max(len(ln) for ln in lines) if lines else 0
    lines = [ln.ljust(w, ".") for ln in lines]
    pad = ["." * w] * (ROWS - len(lines))
    return pad + lines


def flat(w, h=2):
    return blk("\n".join(["X" * w] * h))


def gap(w):
    return blk("." * w)


def hcat(*chunks):
    return ["".join(rows) for rows in zip(*chunks)]


# ============================== WORLD 1: GREEN HILLS ==============================

def build_1_1():
    """Rolling Meadow — gentle intro: coins, first power-up, easy enemies."""
    return hcat(
        blk("""
.....................
.....................
.........C...........
....P...?M?......[]..
.................{}..
XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..............
....CCC.......
..............
.......E...[].
...........{}.
...E.......{}.
XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
"""),
        blk("""
................
...B?B..........
............CC..
................
....E..K........
XXXXXXXX...XXXXX
XXXXXXXX...XXXXX
"""),
        blk("""
.....................
....CCCC.............
...BBBBBB?B..........
.....................
..............E..E...
.........A...........
XXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..................
.......CC.........
......C..C........
.....C....C.......
....C......C......
XXXXX......XXXXXXX
XXXXX......XXXXXXX
"""),
        blk("""
....................
..?...M...?.........
....................
......E...E..K......
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
....................
...............C....
..........CC..C.....
....==...C..C.......
XXXXXX...XXXXX...XXX
XXXXXX...XXXXX...XXX
"""),
        blk("""
......................
..................F...
......................
......................
............==........
...........===........
..........====........
....E....=====........
........======........
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        flat(8),
    )


def build_1_2():
    """Dewdrop Cave — underground coin pockets and first Spiny."""
    ceil = "X" * 12
    return hcat(
        blk(f"""
XXXXXXXXXXXX
............
............
............
....P.......
............
............
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXX
....................
....................
..CCC...............
..BBB....CCC........
.........BBB....M...
....................
.....E.......E......
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXX
................
................
.......CC.......
......----......
................
..S.............
XXXXX......XXXXX
XXXXX......XXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXX
....................
...C..C..C..........
...-..-..-..........
............====....
....................
.......E....C.C.....
XXXX...XXXXXXXXXXXXX
XXXX...XXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
..U...............
.......CCCC....A..
.......BBBB.......
..................
....S.......E.....
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
......C....C......
.....---..---.....
..................
..E...........S...
XXXXX...XX...XXXXX
XXXXX...XX...XXXXX
"""),
        blk("""
XXXXXXXXXXXXXX......
....................
..................F.
....CC..............
....==..............
..==................
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_1_3():
    """Treetop Hop — first athletic level: platforms over pits, Flits."""
    return hcat(
        blk("""
..........
....P.....
XXXXXXXXXX
XXXXXXXXXX
"""),
        blk("""
....................
.........CC.........
....---......---....
..............W.....
....................
....................
....................
....................
XX..................
XX..................
"""),
        blk("""
......................
...C.C................
..=====....o....===...
......................
.............W........
......................
......................
......................
......................
......................
"""),
        blk("""
....................
.....CCC............
....?M?......---....
....................
.......W............
..---.......E.......
...........=====....
....................
....................
....................
"""),
        blk("""
......................
..........CC..........
...A...C......C.......
..===..-..vv..-..===..
......................
............W.........
......................
......................
......................
......................
"""),
        blk("""
....................
......C..C..........
....o.......o.......
....................
..........W.........
....................
............=====...
.......E............
....................
....................
"""),
        blk("""
..................
....CC............
...====...........
..............F...
.......===........
..................
..................
..................
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_1_4():
    """Snapjaw Keep — first castle: lava, spikes, boss fight."""
    return hcat(
        blk("""
XXXXXXXXXXXX
............
............
............
...P........
............
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
..................
...C.C.C..........
..................
......E......S....
XXXXXXXXX^^XXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXX
....................
....................
.....==....==.......
..C........C........
....................
XXXX....S.......XXXX
XXXXLLLLLLLLLLLLXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
....CCC.....M.....
..................
.....o......o..A..
..................
XXX............XXX
XXXLLLLLLLLLLLLXXX
"""),
        blk("""
XXXXXXXXXXXXXXXX
................
................
.......W........
...C.......C....
....==.....==...
XX............XX
XXLLLLLLLLLLLLXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXXXX
......................
......................
......................
..........*...........
......................
XXX.bbbbbbbbbbbbb..XXX
XXXLLLLLLLLLLLLLLLLXXX
"""),
        flat(6),
    )


# ============================== WORLD 2: SANDY DUNES ==============================

def build_2_1():
    """Dune Dash — rolling dunes, plant pipes, momentum."""
    return hcat(
        blk("""
...............
...P......C....
..........C....
XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
"""),
        blk("""
....................
.........CC.........
...()...........()..
...{}....E......{}..
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..................
.......CCC........
......?M?.........
..................
..S...........S...
XXXXXXX....XXXXXXX
XXXXXXX....XXXXXXX
"""),
        blk("""
....................
............CC......
....XXXX............
....XXXX..XXXX......
..E.XXXX..XXXX..E...
XXXXXXXX..XXXXXXXXXX
XXXXXXXX..XXXXXXXXXX
"""),
        blk("""
......................
...C..C..C............
......................
...B..B..B....A..()...
..............   {}...
......K...........{}..
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
....................
.........CCC........
........C...C.......
.......C.....C......
XXXXXX........XXXXXX
XXXXXX........XXXXXX
"""),
        blk("""
......................
...?.....?............
.................F....
.....S.....===........
.........====.........
...E....=====.........
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_2_2():
    """Oasis Pipes — pipe maze with Chomp Plants and shell fun."""
    return hcat(
        blk("""
..............
...P..........
..........[]..
..........{}..
XXXXXXXXXXXXXX
XXXXXXXXXXXXXX
"""),
        blk("""
....................
......CCC...........
....................
..().......()...E...
..{}.......{}.......
..{}...K...{}.......
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..................
.....B?BMB?B......
..................
..................
...E....E.....()..
..............{}..
XXXXXX...XXXXXXXXX
XXXXXX...XXXXXXXXX
"""),
        blk("""
....................
.......CC...CC......
......----.----.....
....................
..()....A.......()..
..{}....... ....{}..
XXXXXXXXX...XXXXXXXX
XXXXXXXXX...XXXXXXXX
"""),
        blk("""
..................
...C..C..C..C.....
..................
..B..B..B..B......
.............K....
....K.............
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
......................
...U.............F....
......................
...........===........
..().....====.........
..{}....=====.........
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_2_3():
    """Sky Ruins — athletic ruins in the sky, moving platforms."""
    return hcat(
        blk("""
..........
...P......
XXXXXXXXXX
XXXXXXXXXX
"""),
        blk("""
....................
......CC............
..====......o.......
....................
..........W.........
....................
....................
....................
....................
....................
"""),
        blk("""
....................
....C.C.C...........
...=======..........
..............vv....
......S.............
....................
....................
....................
....................
....................
"""),
        blk("""
......................
...CCC.......CC.......
..?M?.................
.............---......
..====....W...........
...............W......
.......o..............
......................
......................
......................
"""),
        blk("""
....................
.....A....C..C......
..====....-..-......
....................
........W.....W.....
....................
....o.......o.......
....................
....................
....................
"""),
        blk("""
..................
...C..C...........
..=======.........
......S...........
...........vv.....
..................
..................
..................
..................
..................
"""),
        blk("""
....................
..........CC........
....===...........F.
..................
.........====.......
....................
....................
....................
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_2_4():
    """Sunbaked Citadel — spike gauntlet castle, tougher boss."""
    return hcat(
        blk("""
XXXXXXXXXXXX
............
............
...P........
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXX
....................
...C.C.C............
....................
......E....S....E...
XXXX^^XXXX^^XXXX^^XX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
.....CC....CC.....
....====..====....
..................
..W.....S.....W...
XX..............XX
XXLLLLLLLLLLLLLLXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
...M....CCC....A..
..................
....o.......o.....
..................
XX....^^^^....XXXX
XXLLLLLLLLLLLLXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
..().....C....()..
..{}....===...{}..
..................
.....S.....S......
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXXXX
......................
......................
......................
..........*...........
......................
XXX.bbbbbbbbbbbbb..XXX
XXXLLLLLLLLLLLLLLLLXXX
"""),
        flat(6),
    )


# ============================== WORLD 3: FROSTPEAK ==============================

def build_3_1():
    """Slippery Slopes — ice physics, shell chaos, wide jumps."""
    return hcat(
        blk("""
...............
...P.....CC....
XXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX
"""),
        blk("""
....................
.......?M?..........
....................
...K........K...E...
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
..................
........CCC.......
.......C...C......
......C.....C.....
XXXXXX.......XXXXX
XXXXXX.......XXXXX
"""),
        blk("""
....................
...CC......CC.......
...==......==.......
.........E......E...
XXXXXX....XXXXXXXXXX
XXXXXX....XXXXXXXXXX
"""),
        blk("""
......................
....B?B....A..........
......................
..E......K......K.....
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
....................
.....C..C..C........
....................
XXXX...XXX...XXXXXXX
XXXX...XXX...XXXXXXX
"""),
        blk("""
......................
...................F..
......................
.....==...............
..........====........
..E..........=====....
XXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_3_2():
    """Crystal Cavern — icy underground, tight jumps, Spinies."""
    return hcat(
        blk("""
XXXXXXXXXXXX
............
............
....P.......
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
...CCC............
...BBB.....M......
..................
.....S........S...
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
......C..C........
.....--..--.......
..................
..E...........E...
XXXXX...XX...XXXXX
XXXXX...XX...XXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXX
....................
..U....CCCC.........
.......BBBB....A....
....................
....S.........K.....
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
....C...C...C.....
...---.---.---....
..................
..S....... ...S...
XXXX...XXX...XXXXX
XXXX...XXX...XXXXX
"""),
        blk("""
XXXXXXXXXXXXXX......
....................
..................F.
....CC..............
....==..............
..==......E.........
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_3_3():
    """Blizzard Heights — icy athletic gauntlet before the fortress."""
    return hcat(
        blk("""
..........
...P......
XXXXXXXXXX
XXXXXXXXXX
"""),
        blk("""
....................
......CC............
..====......====....
..........W.........
....................
....................
....................
....................
....................
....................
"""),
        blk("""
....................
...C.C..............
....o.......o.......
.........W..........
....................
............====....
.......W............
....................
....................
....................
"""),
        blk("""
......................
....CCC......A........
...?M?......====......
......................
.....W..........W.....
..----................
.............vv.......
......................
......................
......................
"""),
        blk("""
....................
......C..C..C.......
.....==..==..==.....
....................
...W....S.....W.....
....................
....................
....................
....................
....................
"""),
        blk("""
..................
....CC............
...====...........
..............F...
....o..===........
..................
..................
..................
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        flat(6),
    )


def build_3_4():
    """King Snap's Fortress — the final gauntlet and boss."""
    return hcat(
        blk("""
XXXXXXXXXXXX
............
............
...P........
............
XXXXXXXXXXXX
XXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXX
....................
...C.C.C....M.......
....................
....E....S....E.....
XX^^XXXX^^XXXX^^XXXX
XXXXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
.....C.....C......
....==....==......
.........W........
..W...............
XX..............XX
XXLLLLLLLLLLLLLLXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
...CCC.....A......
..................
....o.....o.......
..................
XX..^^^^^^....XXXX
XXLLLLLLLLLLLLXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXX
..................
..()....CCC...()..
..{}...=====..{}..
..................
....S....W...S....
XXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXX
"""),
        blk("""
XXXXXXXXXXXXXXXXXXXXXXXX
........................
........................
........................
...........*............
........................
XXX.bbbbbbbbbbbbbbb..XXX
XXXLLLLLLLLLLLLLLLLLLXXX
"""),
        flat(6),
    )


# ============================== REGISTRY ==============================

WORLDS = [
    {"name": "Green Hills", "theme": "grass"},
    {"name": "Sandy Dunes", "theme": "desert"},
    {"name": "Frostpeak", "theme": "ice"},
]

LEVELS = [
    {"world": 1, "index": 1, "name": "Rolling Meadow", "theme": "grass",
     "music": "grass", "build": build_1_1, "ice": False, "boss_hp": 0},
    {"world": 1, "index": 2, "name": "Dewdrop Cave", "theme": "cave",
     "music": "grass", "build": build_1_2, "ice": False, "boss_hp": 0},
    {"world": 1, "index": 3, "name": "Treetop Hop", "theme": "grass",
     "music": "grass", "build": build_1_3, "ice": False, "boss_hp": 0},
    {"world": 1, "index": 4, "name": "Snapjaw Keep", "theme": "castle",
     "music": "castle", "build": build_1_4, "ice": False, "boss_hp": 3},
    {"world": 2, "index": 1, "name": "Dune Dash", "theme": "desert",
     "music": "desert", "build": build_2_1, "ice": False, "boss_hp": 0},
    {"world": 2, "index": 2, "name": "Oasis Pipes", "theme": "desert",
     "music": "desert", "build": build_2_2, "ice": False, "boss_hp": 0},
    {"world": 2, "index": 3, "name": "Sky Ruins", "theme": "desert",
     "music": "desert", "build": build_2_3, "ice": False, "boss_hp": 0},
    {"world": 2, "index": 4, "name": "Sunbaked Citadel", "theme": "castle",
     "music": "castle", "build": build_2_4, "ice": False, "boss_hp": 4},
    {"world": 3, "index": 1, "name": "Slippery Slopes", "theme": "ice",
     "music": "ice", "build": build_3_1, "ice": True, "boss_hp": 0},
    {"world": 3, "index": 2, "name": "Crystal Cavern", "theme": "ice",
     "music": "ice", "build": build_3_2, "ice": True, "boss_hp": 0},
    {"world": 3, "index": 3, "name": "Blizzard Heights", "theme": "ice",
     "music": "ice", "build": build_3_3, "ice": True, "boss_hp": 0},
    {"world": 3, "index": 4, "name": "King Snap's Fortress", "theme": "castle",
     "music": "castle", "build": build_3_4, "ice": False, "boss_hp": 5},
]


def level_rows(idx):
    return LEVELS[idx]["build"]()


def validate():
    """Sanity-check every level; returns list of problem strings."""
    problems = []
    for i, lv in enumerate(LEVELS):
        rows = lv["build"]()
        widths = {len(r) for r in rows}
        if len(widths) != 1:
            problems.append(f"{lv['name']}: ragged rows {widths}")
        if len(rows) != ROWS:
            problems.append(f"{lv['name']}: {len(rows)} rows")
        joined = "".join(rows)
        if "P" not in joined:
            problems.append(f"{lv['name']}: no player spawn")
        if lv["boss_hp"] == 0 and "F" not in joined:
            problems.append(f"{lv['name']}: no flag")
        if lv["boss_hp"] > 0 and "*" not in joined:
            problems.append(f"{lv['name']}: no boss")
    return problems
